document.addEventListener("DOMContentLoaded",()=>{
const params=new URLSearchParams(window.location.search);
const concertId=params.get("id");
const concert=(typeof MOCK_CONCERTS!=="undefined"?MOCK_CONCERTS:[]).find(item=>item.id===concertId);
if(!concert){document.querySelector(".ticket-page").innerHTML=`<div class="container" style="padding:48px 0;"><div class="card" style="padding:32px;"><h1>Concert not found</h1><p>Please go back and choose another concert.</p></div></div>`;return;}
const mapData=typeof getConcertMapData==="function"?getConcertMapData(concert.id):null;
const state={selectedZoneId:"",selectedZoneCode:"",selectedTier:"",selectedTicket:null,quantity:0};
const els={banner:document.getElementById("concert-banner"),title:document.getElementById("concert-title"),artist:document.getElementById("concert-artist"),meta:document.getElementById("concert-meta"),map:document.getElementById("concert-map"),categoryList:document.getElementById("category-list"),selectedBox:document.getElementById("selected-ticket"),quantity:document.getElementById("quantity"),total:document.getElementById("total"),minus:document.getElementById("minus"),plus:document.getElementById("plus"),checkoutBtn:document.getElementById("continue-payment")};
function priceToNumber(price){return Number(String(price||"0").replace(/[^\d]/g,""));}
function formatMoney(value){return `$${Number(value||0).toLocaleString("en-US")}`;}
function getStatusMeta(status){const value=String(status||"").toLowerCase();if(value.includes("sold")) return {cls:"sold",label:"Sold Out"};if(value.includes("limit")) return {cls:"limited",label:"Almost Sold Out"};return {cls:"available",label:"Available"};}
function renderHero(){els.banner.src=concert.banner||"";els.banner.alt=concert.title||"Concert Banner";els.title.textContent=concert.title||"Concert";els.artist.textContent=concert.artist||"";els.meta.textContent=`${concert.location||""} • ${concert.date||""} • ${concert.time||""}`;}
function renderMap(){if(!mapData||typeof renderConcertMapLayout!=="function") return;renderConcertMapLayout(els.map,mapData,concert.tickets,state.selectedZoneId);}
function bindMapEvents(){els.map.addEventListener("click",event=>{const zone=event.target.closest&&event.target.closest(".venue-zone");if(!zone||zone.classList.contains("disabled")) return;const tier=zone.dataset.zoneTier;const ticket=typeof getTicketByTier==="function"?getTicketByTier(concert.tickets,tier):null;if(!ticket) return;const status=getStatusMeta(ticket.status);if(status.cls==="sold") return;state.selectedZoneId=zone.dataset.zoneId;state.selectedZoneCode=zone.dataset.zoneCode;state.selectedTier=tier;state.selectedTicket=ticket;state.quantity=state.quantity>0?state.quantity:1;renderMap();updateSelection();});els.map.addEventListener("keydown",event=>{if(event.key!=="Enter"&&event.key!==" ") return;const zone=event.target.closest&&event.target.closest(".venue-zone");if(!zone||zone.classList.contains("disabled")) return;event.preventDefault();zone.click();});}
function renderCategories(){const zonesByTier={vip:[],tier1:[],tier2:[]};(mapData.zones||[]).forEach(zone=>{if(!zonesByTier[zone.tier]) zonesByTier[zone.tier]=[];zonesByTier[zone.tier].push(zone.code);});els.categoryList.innerHTML=(concert.tickets||[]).map(ticket=>{const tier=typeof normalizeTicketTier==="function"?normalizeTicketTier(ticket.type):"tier2";const status=getStatusMeta(ticket.status);return `<div class="category-row"><div class="category-name"><strong>${ticket.type}</strong><span>${getTierLabel(tier)} • Zones: ${(zonesByTier[tier]||[]).join(", ")}</span></div><div class="category-right"><span class="status-pill ${status.cls}">${status.label}</span><strong>${ticket.price}</strong></div></div>`;}).join("");}
function updateSelection(){if(!state.selectedTicket||state.quantity===0){els.selectedBox.innerHTML=`<div class="summary-empty"><strong>No ticket selected</strong><span>Select a zone on the map to continue</span></div>`;els.quantity.textContent="0";els.total.textContent="$0";els.checkoutBtn.disabled=true;return;}const status=getStatusMeta(state.selectedTicket.status);const unitPrice=priceToNumber(state.selectedTicket.price);const total=unitPrice*state.quantity;els.selectedBox.innerHTML=`<div class="selected-ticket-card"><div class="selected-ticket-top"><div><strong>${state.selectedZoneCode}</strong><span>${state.selectedTicket.type}</span></div><span class="status-pill ${status.cls}">${status.label}</span></div><div class="selected-ticket-meta"><div><span>Category</span><strong>${getTierLabel(state.selectedTier)}</strong></div><div><span>Unit Price</span><strong>${formatMoney(unitPrice)}</strong></div></div></div>`;els.quantity.textContent=String(state.quantity);els.total.textContent=formatMoney(total);els.checkoutBtn.disabled=false;}
els.plus.addEventListener("click",()=>{if(!state.selectedTicket) return;state.quantity+=1;updateSelection();});
els.minus.addEventListener("click",()=>{if(!state.selectedTicket) return;state.quantity=Math.max(0,state.quantity-1);if(state.quantity===0){state.selectedZoneId="";state.selectedZoneCode="";state.selectedTier="";state.selectedTicket=null;renderMap();}updateSelection();});
els.checkoutBtn.addEventListener("click",()=>{if(!state.selectedTicket||state.quantity===0) return;const total=priceToNumber(state.selectedTicket.price)*state.quantity;localStorage.setItem("concertlyCheckout",JSON.stringify({concertId:concert.id,zoneCode:state.selectedZoneCode,tier:getTierLabel(state.selectedTier),tickets:[{type:state.selectedTicket.type,price:state.selectedTicket.price,quantity:state.quantity}],total:formatMoney(total)}));window.location.href="../checkout/index.html";});
renderHero();
renderMap();
renderCategories();
bindMapEvents();
updateSelection();
});